
export const metadata = {
  title: "All users",
  description: "Generated by create next app",
};
export default function layout({children}){

    return(
        <div>
            {children} 
        </div>
    )
}