import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       >
        <nav>
          <ul className=" flex ">
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/about'>about</Link></li>
            <li><Link href='/about/mission'>mission</Link></li>
            <li><Link href='/users'>users</Link></li>
            <li><Link href='/posts'>posts</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
